package com.wzu.springboot.dao;

import com.wzu.springboot.pojo.Detail;
import java.util.List;

public interface DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    Detail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    List<Detail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int updateByPrimaryKey(Detail record);
}