package com.wzu.springboot.dao;

import com.wzu.springboot.pojo.Theme;
import java.util.List;

public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int insert(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    Theme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    List<Theme> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int updateByPrimaryKey(Theme record);
}