package com.wzu.springboot.dao;

import com.wzu.springboot.pojo.Trippicture;
import java.util.List;

public interface TrippictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int insert(Trippicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    Trippicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    List<Trippicture> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trippicture
     *
     * @mbggenerated Mon Jun 17 08:41:45 CST 2019
     */
    int updateByPrimaryKey(Trippicture record);
}